$(document).ready(function(){
		$('.sp1').mouseenter(function(){
			$('.name1').stop().fadeIn()
			$('.name4').stop().fadeOut()
			});
		$('.sp1').mouseleave(function(){
			$('.name1').stop().fadeOut()
			$('.name4').stop().fadeIn()
			});
		$('.sp2').mouseenter(function(){
			$('.name2').stop().fadeIn()
			$('.name4').stop().fadeOut()
			});
		$('.sp2').mouseleave(function(){
			$('.name2').stop().fadeOut()
			$('.name4').stop().fadeIn()
			});
		$('.sp3').mouseenter(function(){
			$('.name3').stop().fadeIn()
			$('.name4').stop().fadeOut()
			});
		$('.sp3').mouseleave(function(){
			$('.name3').stop().fadeOut()
			$('.name4').stop().fadeIn()
			});
		$('.sp4').mouseenter(function(){
			$('.name4').stop().fadeIn()
			});
		
		$('.sp5').mouseenter(function(){
			$('.name5').stop().fadeIn()
			$('.name4').stop().fadeOut()
			});
		$('.sp5').mouseleave(function(){
			$('.name5').stop().fadeOut()
			$('.name4').stop().fadeIn()
			});
		$('.sp6').mouseenter(function(){
			$('.name6').stop().fadeIn()
			$('.name4').stop().fadeOut()
			});
		$('.sp6').mouseleave(function(){
			$('.name6').stop().fadeOut()
			$('.name4').stop().fadeIn()
			});
		$('.sp7').mouseenter(function(){
			$('.name7').stop().fadeIn()
			$('.name4').stop().fadeOut()
			});
		$('.sp7').mouseleave(function(){
			$('.name4').stop().fadeIn()
			$('.name7').stop().fadeOut()
			});
});